import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.scss"


export const metadata = {
  title: "Hornet Softent",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
